// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Employee.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EmployeeMessages {
  public static partial class EmployeeService
  {
    static readonly string __ServiceName = "EmployeeMessages.EmployeeService";

    static readonly grpc::Marshaller<global::EmployeeMessages.GetEmployeeRequest> __Marshaller_EmployeeMessages_GetEmployeeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EmployeeMessages.GetEmployeeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EmployeeMessages.GetEmployeeResponse> __Marshaller_EmployeeMessages_GetEmployeeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EmployeeMessages.GetEmployeeResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::EmployeeMessages.GetEmployeeRequest, global::EmployeeMessages.GetEmployeeResponse> __Method_GetEmployee = new grpc::Method<global::EmployeeMessages.GetEmployeeRequest, global::EmployeeMessages.GetEmployeeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetEmployee",
        __Marshaller_EmployeeMessages_GetEmployeeRequest,
        __Marshaller_EmployeeMessages_GetEmployeeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EmployeeMessages.EmployeeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EmployeeService</summary>
    [grpc::BindServiceMethod(typeof(EmployeeService), "BindService")]
    public abstract partial class EmployeeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::EmployeeMessages.GetEmployeeResponse> GetEmployee(global::EmployeeMessages.GetEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EmployeeService</summary>
    public partial class EmployeeServiceClient : grpc::ClientBase<EmployeeServiceClient>
    {
      /// <summary>Creates a new client for EmployeeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EmployeeServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EmployeeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EmployeeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EmployeeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EmployeeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::EmployeeMessages.GetEmployeeResponse GetEmployee(global::EmployeeMessages.GetEmployeeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetEmployee(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EmployeeMessages.GetEmployeeResponse GetEmployee(global::EmployeeMessages.GetEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetEmployee, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EmployeeMessages.GetEmployeeResponse> GetEmployeeAsync(global::EmployeeMessages.GetEmployeeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetEmployeeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EmployeeMessages.GetEmployeeResponse> GetEmployeeAsync(global::EmployeeMessages.GetEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetEmployee, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EmployeeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EmployeeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EmployeeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetEmployee, serviceImpl.GetEmployee).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EmployeeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetEmployee, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EmployeeMessages.GetEmployeeRequest, global::EmployeeMessages.GetEmployeeResponse>(serviceImpl.GetEmployee));
    }

  }
}
#endregion
